[profile.default]
libs = ['lib']
solc_version = '0.8.20'
evm_version = 'shanghai'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
fuzz_runs = 1_000

fs_permissions = [{ access = 'read-write', path = '/'}]

remappings = [
  "forge-std=lib/forge-std/src/",
  "foundry-huff=lib/foundry-huff/src/",
  "@chainlink-2.6.0=lib/chainlink-2.6.0/",
  "@clones-with-immutable-args=lib/clones-with-immutable-args/",
  "@openzeppelin-4.9.2=lib/openzeppelin-contracts-4.9.2/"
]

ignored_warnings_from = [
  "src/dai-plus-plus/Account.sol",
  "src/dai-plus-plus/AccountManager.sol",
  "src/dai-plus-plus/Stablecoin.sol",
  "src/dai-plus-plus/SystemConfiguration.sol"
]
